model {
  file: "model.sdf"
}
name: "Design_Ideas_Drawer_Store_Organizer"
description: "Design Ideas Drawer Store Organizer"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Design Ideas"
}
annotations {
  key: "gtin"
  value: "00095787140780"
}
annotations {
  key: "sku"
  value: "00095787140780"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
