model {
  file: "model.sdf"
}
name: "Toys_R_Us_Treat_Dispenser_Smart_Puzzle_Foobler"
description: "Toys R Us Treat Dispenser, Smart Puzzle, Foobler"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Toys R Us"
}
annotations {
  key: "gtin"
  value: "00737257593497"
}
annotations {
  key: "sku"
  value: "00737257593497"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
